In [40]:
# import os
# print(f"✅ 현재 위치 : {os.getcwd()}")

# 클래스 코드 수정시 캐시된 파이선파일 재설정
import model1
import imp
imp.reload(model1)
import numpy as np
# 클래스 불러오기
import model1
from model1 import *

# 모델 인스턴스 생성
abalone = Model_1()

# 데이터 불러오기
csv_path = 'D:/coding/aib/GPTeachersDay/TeamProject1/leeyeonjun/Data/Regression_data.csv'
df, X, y, X_train, X_test, y_train, y_test = abalone.load_data(csv_path)

# 모델 빌드
model = abalone.get_model(len(X_train.columns))

In [19]:
# 저장된 가중치 불러와서 테스트데이터 평가
model.load_weights('model1.h5')
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss : {loss:.3f}\nAccuracy  : {accuracy:.3f}')

26/26 [==============================] - 1s 18ms/step - loss: 5.9746 - accuracy: 0.9290
Test Loss : 5.975
Accuracy  : 0.929

In [27]:
# 학습 기록 json 확인
import json
with open('model1.json') as json_file:
    json_file = json.loads(json_file.read())
model1_hist = pd.DataFrame(json_file)
print(f'{model1_hist[:5]}\n\n{model1_hist[-5:]}')

         loss  accuracy    val_loss  val_accuracy    lr
0  104.739456  0.026527  103.417572      0.041034  0.01
1   96.350578  0.069788   97.721985      0.072277  0.01
2   90.166565  0.102865   92.975227      0.099878  0.01
3   84.790787  0.136617   88.345688      0.127309  0.01
4   79.610855  0.174622   83.325569      0.157843  0.01

         loss  accuracy  val_loss  val_accuracy            lr
995  3.357505  0.873484  5.675055      0.842085  6.169000e-07
996  3.429576  0.867115  5.675645      0.842068  3.949000e-07
997  3.375049  0.857659  5.676090      0.842054  2.220000e-07
998  3.333688  0.852802  5.677863      0.842042  9.860000e-08
999  3.395898  0.855940  5.678136      0.842013  2.470000e-08

In [29]:
# 최적모델로 저장된 에포크 확인
model1_hist.sort_values(by=['val_accuracy'], ascending=False)[:5]

         loss  accuracy  val_loss  val_accuracy        lr
188  4.504435  0.851636  6.011819      0.851097  0.009153
288  4.092480  0.863976  6.004257      0.850930  0.008089
187  4.552999  0.845662  6.252081      0.850777  0.009162
286  4.123647  0.854644  6.353249      0.850152  0.008114
287  4.102179  0.852626  5.639835      0.849797  0.008102

In [7]:
len(X_train.columns)

12

In [8]:
X.describe().loc[['mean', 'min', '50%', 'max']]

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Area,Perimeter,Sex_F,Sex_I,Sex_M
mean,0.527256,0.41047,0.140462,0.840869,0.363263,0.182497,0.241525,0.178895,1.484664,0.318001,0.312282,0.369717
min,0.110000,0.09000,0.000000,0.008000,0.002500,0.000500,0.003000,0.007775,0.315726,0.000000,0.000000,0.000000
50%,0.545000,0.42500,0.145000,0.811750,0.341250,0.172500,0.236000,0.183587,1.542143,0.000000,0.000000,0.000000
max,0.815000,0.65000,1.130000,2.825500,1.488000,0.760000,1.005000,0.416065,2.315766,1.000000,1.000000,1.000000

In [9]:
X.describe()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Area,Perimeter,Sex_F,Sex_I,Sex_M
count,4022.000000,4022.000000,4022.000000,4022.000000,4022.000000,4022.000000,4022.000000,4022.000000,4022.000000,4022.000000,4022.000000,4022.000000
mean,0.527256,0.410470,0.140462,0.840869,0.363263,0.182497,0.241525,0.178895,1.484664,0.318001,0.312282,0.369717
std,0.117982,0.097604,0.041455,0.488602,0.220715,0.109262,0.138670,0.073314,0.338807,0.465758,0.463482,0.482788
min,0.110000,0.090000,0.000000,0.008000,0.002500,0.000500,0.003000,0.007775,0.315726,0.000000,0.000000,0.000000
25%,0.455000,0.350000,0.115000,0.454625,0.190500,0.096000,0.134500,0.125467,1.277329,0.000000,0.000000,0.000000
50%,0.545000,0.425000,0.145000,0.811750,0.341250,0.172500,0.236000,0.183587,1.542143,0.000000,0.000000,0.000000
75%,0.615000,0.480000,0.165000,1.162500,0.506500,0.255375,0.330000,0.233165,1.737169,1.000000,1.000000,1.000000
max,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,0.416065,2.315766,1.000000,1.000000,1.000000

In [42]:
test_input = list(X.describe().loc[['mean']].values[0][:-3])
print(f'테스트 인풋값 : {np.round(test_input, 3)}')

result = abalone.input_predict(test_input, 1) # 암컷[1] 수컷[2] 새끼[3]
print(f'예상되는 전복연령 : {result}')

테스트 인풋값 : [0.527 0.41  0.14  0.841 0.363 0.182 0.242 0.179 1.485]

c:\Users\leeyeonjun85\.conda\envs\p310_1\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

예상되는 전복연령 : 9